---
title: "Replication Mixture Notes"
fontsize: 12pt
papersize: a4
geometry:
  - top=2cm
  - bottom=2cm
  - left=2cm
  - right=2cm
  - marginparwidth=1.75cm
urlcolor: blue
---

\section{Intro}

Let $\theta$ denote an unknown effect size and $\hat{\theta}_i$ an estimate measured from study $i\in\left\{o,r\right\}$. Furthermore, let assume a Gaussian likelihood for the effect estimates \begin{align*}
    \hat{\theta}_i\mid \theta \sim N(\theta, \sigma^2_i),
\end{align*} with $i\in\left\{o,r\right\}$. Let consider the following scenario \begin{align*}
    \hat{\theta}_r\mid \theta &\sim N(\theta,\sigma^2_r) \\
    \theta \mid \omega, \hat{\theta}_0, \mu &\sim \omega N(\hat{\theta}_0,\sigma^2_0) + (1-\omega) N(\mu,\tau^2) \\
    \omega &\sim Beta(\alpha, \beta) 
\end{align*} \noindent The posterior is \begin{align*}
    \pi(\theta, \omega \mid \hat{\theta}_r) = \dfrac{N(\hat{\theta}_r\mid \theta, \sigma_r^2)\pi(\theta\mid \omega)\pi(\omega)}{\int_\Omega \int_\Theta N(\hat{\theta}_r\mid \theta, \sigma_r^2)\pi(\theta\mid \omega)\pi(\omega) d\theta d\omega} 
\end{align*} The \textbf{normalizing constant} is

\begin{align*}
    f(\hat{\theta}_r) &= \int_\Omega \int_\Theta N(\hat{\theta}_r \mid \theta, \sigma_r^2) \times \left\{\omega N(\theta\mid \hat{\theta}_0, \sigma_0^2) +(1-\omega)N(\theta \mid \mu, \tau^2)\right\} \times Beta(\omega \mid \alpha, \beta) d \theta d \omega \\
    &= \int_\Omega Beta(\omega \mid \alpha, \beta) \int_\Theta N(\hat{\theta}_r \mid \theta, \sigma_r^2) \times \left\{\omega N(\theta\mid \hat{\theta}_0, \sigma_0^2) +(1-\omega)N(\theta \mid \mu, \tau^2)\right\} d \theta d \omega \\
    &= \int_\Omega Beta(\omega \mid \alpha, \beta) \int_\Theta \omega \times \underbrace{N(\hat{\theta}_r \mid \theta, \sigma_r^2) N(\theta\mid \hat{\theta}_0, \sigma_0^2)}_{\text{Update}} +(1-\omega)\times \underbrace{N(\hat{\theta}_r \mid \theta, \sigma_r^2) N(\theta \mid \mu, \tau^2)}_{\text{Update}} d \theta d \omega \\
    &=\int_\Omega Beta(\omega \mid \alpha, \beta) \times \left\{ \omega N(\hat{\theta}_r\mid \sigma_r^2+\sigma_0^2) + (1-\omega)N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\} d\omega
\end{align*} \newpage \noindent Then the **joint posterior** can be rewritten as \begin{align*}
     \pi(\theta, \omega \mid \hat{\theta}_r) &= \dfrac{N(\hat{\theta}_r\mid \theta, \sigma^2_r)\pi(\theta\mid \omega)\pi(\omega)}{f(\hat{\theta}_r)} \\
     &= \dfrac{N(\hat{\theta}_r \mid \theta, \sigma^2_r)\times\left\{\omega N(\theta \mid \hat{\theta}_0, \sigma^2_r +\sigma^2_0)+ (1-\omega)N(\theta \mid \mu, \tau^2)\right\}\times Beta(\omega \mid \alpha, \beta)}{\int_\Omega Beta(\omega \mid \alpha, \beta) \times \left\{ \omega N(\hat{\theta}_r, \sigma_r^2+\sigma_0^2) + (1-\omega)N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\} d\omega}
\end{align*} \noindent The **marginal posterior** for $\omega$ is \begin{align*}
    \pi(\omega \mid \hat{\theta}_r) &= \int_\Theta \pi(\theta, \omega \mid \hat{\theta}_r) d\theta\\
    &= \bigintsss_\Theta \dfrac{N(\hat{\theta}_r \mid \theta, \sigma^2_r)\times\left\{\omega N(\theta \mid \hat{\theta}_0, \sigma^2_0)+ (1-\omega)N(\theta \mid \mu, \tau^2)\right\}\times Beta(\omega \mid \alpha, \beta)}{f(\hat{\theta}_r)} d\theta\\
    &= \dfrac{Beta(\omega \mid \alpha, \beta) \times \left\{ \omega N(\hat{\theta}_r, \sigma_r^2+\sigma_0^2) + (1-\omega)N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\}}{\int_\Omega Beta(\omega \mid \alpha, \beta) \times \left\{ \omega N(\hat{\theta}_r, \sigma_r^2+\sigma_0^2) + (1-\omega)N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\} d\omega}
\end{align*} The \textbf{marginal posterior} for $\theta$ is \begin{align*}
\pi(\theta \mid \hat{\theta}_r) &= \int_{\omega} \pi(\theta, \omega \mid \hat{\theta}_r) d\omega \\
&= \bigintsss_{\Omega} \dfrac{N(\hat{\theta}_r \mid \theta, \sigma^2_r)\times\left\{\omega N(\theta \mid \hat{\theta}_0, \sigma^2_0) + (1-\omega)N(\theta \mid \mu, \tau^2)\right\}\times Beta(\omega \mid \alpha, \beta)}{f(\hat{\theta}_r)}d\omega
\end{align*} Let focus on the **numerator** \footnotesize \begin{align*}
   &= \int_\Omega N(\hat{\theta}_r \mid \theta, \sigma^2_r) \left\{\omega N(\theta \mid \hat{\theta}_0, \sigma^2_0)+(1-\omega)N(\theta \mid \mu, \tau^2)\right\}Beta(\omega \mid \alpha, \beta) d\omega \\
    &= N(\hat{\theta}_r \mid \theta, \sigma^2_r) \times \left(\int_\Omega \omega N(\theta \mid \hat{\theta}_0, \sigma^2_0)Beta(\omega \mid \alpha, \beta)d\omega + \int_\Omega N(\theta \mid \mu, \tau^2)Beta(\omega \mid \alpha, \beta)d\omega -\int_\Omega \omega N(\theta \mid \mu, \tau^2)Beta (\omega \mid \alpha, \beta) d\omega\right) \\
    &= N(\hat{\theta}_r \mid \theta, \sigma^2_r)\times\left(N(\theta \mid \hat{\theta}_0, \sigma^2_0) \underbrace{\int_\Omega \omega Beta(\omega \mid \alpha, \beta) d\omega}_{\mathbb{E}(\omega)} + N(\theta \mid \mu, \tau^2) \underbrace{\int_\Omega Beta(\omega \mid \alpha, \beta)d\omega}_{1} - N(\theta \mid \mu, \tau^2)\underbrace{\int_{\Omega}\omega Beta (\omega \mid \alpha, \beta)d\omega}_{\mathbb{E}(\omega)}\right) \\
    &= N(\hat{\theta}_r \mid \theta, \sigma^2_r) \times \left(\mathbb{E}_{\Omega}(\omega)\left\{N(\theta \mid \hat{\theta}_0,\sigma^2_0)-N(\theta \mid \mu, \tau^2)\right\}+N(\theta \mid \mu, \tau^2)\right)
\end{align*} \normalsize Then the \textbf{marginal posterior} with respect to $\theta$ is \begin{align*}
\pi(\theta \mid \hat{\theta}_r) = &= \int_{\omega} \pi(\theta, \omega \mid \hat{\theta}_r) d\omega \\
&= \bigintsss_{\Omega} \dfrac{N(\hat{\theta}_r \mid \theta, \sigma^2_r)\times\left\{\omega N(\theta \mid \hat{\theta}_0, \sigma^2_0) + (1-\omega)N(\theta \mid \mu, \tau^2)\right\}\times Beta(\omega \mid \alpha, \beta)}{f(\hat{\theta}_r)} d\omega\\
&= \dfrac{N(\hat{\theta}_r \mid \theta, \sigma^2_r) \times \left(\mathbb{E}_{\Omega}(\omega)\left\{N(\theta \mid \hat{\theta}_0,\sigma^2_0)-N(\theta \mid \mu, \tau^2)\right\}+N(\theta \mid \mu, \tau^2)\right)}{f(\hat{\theta}_r)}
\end{align*} Let us examine whether we can simplify the normalizing constant. \begin{align*}
f(\hat{\theta}_r) &= \int_\Omega Beta(\omega \mid \alpha, \beta) \times \left\{ \omega N(\hat{\theta}_r\mid \hat{\theta}_0, \sigma^2_r +\sigma^2_0) + (1-\omega)N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\} d\omega \\
&= \int_\Omega Beta(\omega \mid \alpha, \beta) \times \left\{\omega N(\hat{\theta}_r \mid \hat{\theta}_0, \sigma^2_r +\sigma^2_0) + N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2 ) - \omega N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\} d \omega \\
&= N(\hat{\theta}_r \mid \hat{\theta}_0, \sigma^2_r +\sigma^2_0) \times \int_\Omega \omega Beta(\omega \mid \alpha, \beta) d\omega + N(\hat{\theta}_r \mid \mu , \sigma^2_r + \tau^2) \times \int_\Omega Beta(\omega \mid \alpha, \beta) d\omega \\ 
 &- N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2) 
 \times \int_\Omega \omega Beta(\omega \mid \alpha, \beta) d\omega \\
 &= \mathbb{E}_{\Omega}(\omega) N(\hat{\theta}_r \mid \hat{\theta}_0, \sigma^2_r +\sigma^2_0) + N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2) - \mathbb{E}_{\Omega}(\omega) N(\hat{\theta}_r \mid \mu , \sigma^2_r + \tau^2) \\
 &= \mathbb{E}_{\Omega}(\omega) \times \left\{N(\hat{\theta}_r \mid \hat{\theta}_0, \sigma^2_r +\sigma^2_0)-N(\hat{\theta}_r \mid \mu, \sigma^2_r + \tau^2)\right\} + N(\hat{\theta}_r \mid \mu, \sigma^2_r+ \tau^2)
\end{align*}
